on:
  push:

jobs:
  node-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache node
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: run lint
        run: npm run lint

      - name: Run tests
        run: node test.js
